#ifndef TOKENIZER_FFI_H
#define TOKENIZER_FFI_H

/* This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialize the tokenizer with cl100k_base encoding
 * Returns 0 on success, -1 on failure
 */
int tokenizer_initialize(void);

/**
 * Count tokens in the given text
 * Returns the token count, or -1 on error
 */
int tokenizer_count_tokens(const char *text);

/**
 * Encode text to tokens
 * Returns the number of tokens, fills the tokens array
 * tokens_buffer must be pre-allocated with sufficient size
 */
int tokenizer_encode(const char *text, int *tokens_buffer, size_t buffer_size);

/**
 * Decode tokens back to text
 * Returns a null-terminated C string that must be freed by the caller
 */
char *tokenizer_decode(const int *tokens, size_t token_count);

/**
 * Free a string returned by tokenizer_decode
 */
void tokenizer_free_string(char *s);

/**
 * Check if the tokenizer is initialized
 */
int tokenizer_is_ready(void);

#endif /* TOKENIZER_FFI_H */
