use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let output_path = PathBuf::from(&crate_dir).join("include");
    
    // Create include directory if it doesn't exist
    std::fs::create_dir_all(&output_path).unwrap();
    
    // Generate C header using cbindgen
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("TOKENIZER_FFI_H")
        .with_autogen_warning("/* This file is auto-generated by cbindgen. Do not edit manually. */")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(output_path.join("tokenizer_ffi.h"));
    
    println!("cargo:rerun-if-changed=src/lib.rs");
}